// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (unpooled) connection: the advisory lock
    // they take to prevent concurrent migrations doesn't survive Neon's
    // pooled/PgBouncer connections, which reuse the underlying session
    // between statements. DIRECT_URL falls back to DATABASE_URL for local
    // dev, where there's no pooler and the two are the same.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
